___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___

In this assignment you will start off with Numpy Exercises and then complete the whole Exercise with Pandas questions. All the subjects related to questions here already covered in preclass materials and in-class sessions. So good luck!


#### 1. Import NumPy Library

In [23]:
import numpy as np

#### 2. Create an array from my_list=[5,10,15,20,25]

In [24]:
my_list=[5,10,15,20,25]
np.array(my_list)

array([ 5, 10, 15, 20, 25])

#### 3. Generate an array of 5x5 with zeros 

In [25]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

#### 4. Generate an array of 4x4 with ones and assign data type as int

In [26]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

#### 5. Make all the values of the array above 7

In [27]:
np.ones((4,4))*7

array([[7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.],
       [7., 7., 7., 7.]])

#### 6. Create thr previous array above by full() method

In [28]:
np.full((4,4),7)

array([[7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7],
       [7, 7, 7, 7]])

#### 7. Create an array of even integers from 2 to 16 (inclusive) 

In [29]:
np.arange(2,17,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16])

#### 8. Create a 5x5 matrix with the values between 0 to 25 (exclusive)

In [30]:
np.arange(0,25).reshape(5,5)


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 9. Create a 5x5 matrix with the values between 0 to 25 (exclusive) using linspace

In [31]:
np.linspace(0,24,25,dtype=int).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### 10. Create randomly 5 numbers with numpy

In [32]:
np.random.rand(5)

array([0.21388688, 0.78896365, 0.39833001, 0.59864028, 0.77903409])

#### 11. Create an array of 5*5 shape and fills it with random values as per the standard normal distribution

In [33]:
rand_num = np.random.normal(0,1,25).reshape(5,5)
print("25 random numbers from a standard normal distribution:")
print(rand_num)

25 random numbers from a standard normal distribution:
[[-0.46438147  0.24125179  2.76798158 -0.28160564  0.46062784]
 [ 0.08879439 -0.66006657 -0.09325242 -1.43104077  0.83989782]
 [ 0.9782478  -0.38101419 -1.17051967 -0.7466619   0.13144711]
 [-0.09187233 -0.3609525   0.34135662 -1.79508537 -0.6681834 ]
 [-0.20014466  0.09083837 -0.18496704 -0.09605358  0.28949278]]


In [34]:
# addition
a = np.random.randn(5,5)
a

array([[ 0.19152383,  0.49112926,  1.11534288, -0.80252797, -0.19323315],
       [-0.5799727 , -1.21409933, -0.02764484, -2.11110992,  0.80777541],
       [-0.45735919,  0.71436663, -0.39690465,  0.66863362, -0.83903075],
       [ 0.45895558, -1.88798342, -0.8217557 ,  1.80313263,  1.47902257],
       [-1.04408039,  0.55577729, -0.69797368,  0.30436425, -0.004628  ]])

#### 12. Create a 3*4 array of random int numbers between 20 and 50

In [35]:
array = np.random.randint(20,[50], size = (3,4))
array

array([[42, 42, 40, 37],
       [46, 20, 26, 35],
       [45, 35, 48, 45]])

#### 13. Reshape the array below with the shape of 6x8

In [36]:
ranarr = np.random.randint(2,[53], size = 48)

In [37]:
ranarr

array([42, 31, 33, 31, 48, 45, 12, 15, 14, 20, 43, 35, 14, 33, 13, 27,  3,
       49, 50, 32, 13, 20, 12,  7, 12, 14, 46,  3,  2, 40, 42, 13, 51, 52,
        3, 46,  9, 51,  7, 46,  2, 18,  9,  4, 34, 16, 47, 49])

In [38]:
ranarr.reshape(6,8)

array([[42, 31, 33, 31, 48, 45, 12, 15],
       [14, 20, 43, 35, 14, 33, 13, 27],
       [ 3, 49, 50, 32, 13, 20, 12,  7],
       [12, 14, 46,  3,  2, 40, 42, 13],
       [51, 52,  3, 46,  9, 51,  7, 46],
       [ 2, 18,  9,  4, 34, 16, 47, 49]])

In [39]:
#reshape with -1
ranarr.reshape(3,-1)

array([[42, 31, 33, 31, 48, 45, 12, 15, 14, 20, 43, 35, 14, 33, 13, 27],
       [ 3, 49, 50, 32, 13, 20, 12,  7, 12, 14, 46,  3,  2, 40, 42, 13],
       [51, 52,  3, 46,  9, 51,  7, 46,  2, 18,  9,  4, 34, 16, 47, 49]])

# -1 girilen sayıya göre boyutu tamamlar size ın katına uygun şekilde.


## Numpy Indexing and Selection


In [40]:
#Create array below
mat= np.arange(1, 17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

#### 14. Using the array above, write a code that reproduces the output shown below.<br>

In [41]:
mat[1:3, [1,2]]

array([[ 6,  7],
       [10, 11]])

#### 15. Get the first column of the array above.

In [42]:
mat[0:4,0]

array([ 1,  5,  9, 13])

#### 16. Get the values in 2nd row for every 2 step.

In [43]:
mat[1, 0:4:2]

array([5, 7])

#### 17.Assign 77 to every cell in 3rd column.

In [44]:
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [45]:
mat[0:4, 2] = [77]
mat


array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

#### 18. Take 2nd row 1st column, 4th row 2nd column.

In [46]:
x = mat[1,0]
y = mat[3,1]
np.stack([x,y])

array([ 5, 14])

#### 19. Take between 2nd and last row with step 2 and between 1st and last column with step 2.

In [47]:
np.array((mat[1, 0:3:2], mat[3, 0:3:2]))

array([[ 5, 77],
       [13, 77]])

## NumPy Operations

#### 20. Get the sum of values smaller than 10 and values bigger than 12 from array above 

In [48]:
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [49]:
mat[mat < 10] 

array([1, 2, 4, 5, 6, 8, 9])

In [50]:
mat[mat > 12]

array([77, 77, 77, 13, 14, 77, 16])

In [55]:
result = mat[mat<10] + mat[mat>12]
result


array([78, 79, 81, 18, 20, 85, 25])

#### 21. Get the standard deviation of the result above

In [56]:
np.std(result)

29.700546274093877

#### 22. Get the sum of the second column from array above

In [34]:
#print array here
mat

array([[ 1,  2, 77,  4],
       [ 5,  6, 77,  8],
       [ 9, 10, 77, 12],
       [13, 14, 77, 16]])

In [57]:
ıkıncı = mat[0:4,1]
np.sum(ıkıncı)


32

#### 23. Get the median, mean and std of 3rd row from array above

In [59]:
mat = np.arange(1, 17).reshape(4,4)
mat

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [60]:
arr = mat[2]
arr

array([ 9, 10, 11, 12])

In [61]:
#median
np.median(arr)

10.5

In [62]:
#mean
np.mean(arr)

10.5

In [63]:
#std
np.std(arr)

1.118033988749895

# Pandas Section

In [64]:
import pandas as pd

**Read Salaries.csv and take a look at the first 5 rows, df info and df statistical measurements**

In [65]:
sal=pd.read_csv('Salaries.csv')

In [66]:
sal.head(5)

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [67]:
sal.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148654 entries, 0 to 148653
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype  
---  ------            --------------   -----  
 0   Id                148654 non-null  int64  
 1   EmployeeName      148654 non-null  object 
 2   JobTitle          148654 non-null  object 
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148654 non-null  float64
 8   TotalPayBenefits  148654 non-null  float64
 9   Year              148654 non-null  int64  
 10  Notes             0 non-null       float64
 11  Agency            148654 non-null  object 
 12  Status            0 non-null       float64
dtypes: float64(8), int64(2), object(3)
memory usage: 14.7+ MB


In [68]:
sal.describe()

Id        BasePay    OvertimePay       OtherPay  \
count  148654.000000  148045.000000  148650.000000  148650.000000   
mean    74327.500000   66325.448841    5066.059886    3648.767297   
std     42912.857795   42764.635495   11454.380559    8056.601866   
min         1.000000    -166.010000      -0.010000   -7058.590000   
25%     37164.250000   33588.200000       0.000000       0.000000   
50%     74327.500000   65007.450000       0.000000     811.270000   
75%    111490.750000   94691.050000    4658.175000    4236.065000   
max    148654.000000  319275.010000  245131.880000  400184.250000   

            Benefits       TotalPay  TotalPayBenefits           Year  Notes  \
count  112491.000000  148654.000000     148654.000000  148654.000000    0.0   
mean    25007.893151   74768.321972      93692.554811    2012.522643    NaN   
std     15402.215858   50517.005274      62793.533483       1.117538    NaN   
min       -33.890000    -618.130000       -618.130000    2011.000000    NaN   
25%     11535.395000   36168.995000      44065.650000    2012.000000    NaN   
50%     28628.620000   71426.610000      92404.090000    2013.000000    NaN   
75%     35566.855000  105839.135000     132876.450000    2014.000000    NaN   
max     96570.660000  567595.430000     567595.430000    2014.000000    NaN   

       Status  
count     0.0  
mean      NaN  
std       NaN  
min       NaN  
25%       NaN  
50%       NaN  
75%       NaN  
max       NaN

In [69]:
sal.describe().T


count          mean           std      min        25%  \
Id                148654.0  74327.500000  42912.857795     1.00  37164.250   
BasePay           148045.0  66325.448841  42764.635495  -166.01  33588.200   
OvertimePay       148650.0   5066.059886  11454.380559    -0.01      0.000   
OtherPay          148650.0   3648.767297   8056.601866 -7058.59      0.000   
Benefits          112491.0  25007.893151  15402.215858   -33.89  11535.395   
TotalPay          148654.0  74768.321972  50517.005274  -618.13  36168.995   
TotalPayBenefits  148654.0  93692.554811  62793.533483  -618.13  44065.650   
Year              148654.0   2012.522643      1.117538  2011.00   2012.000   
Notes                  0.0           NaN           NaN      NaN        NaN   
Status                 0.0           NaN           NaN      NaN        NaN   

                       50%         75%        max  
Id                74327.50  111490.750  148654.00  
BasePay           65007.45   94691.050  319275.01  
OvertimePay           0.00    4658.175  245131.88  
OtherPay            811.27    4236.065  400184.25  
Benefits          28628.62   35566.855   96570.66  
TotalPay          71426.61  105839.135  567595.43  
TotalPayBenefits  92404.09  132876.450  567595.43  
Year               2013.00    2014.000    2014.00  
Notes                  NaN         NaN        NaN  
Status                 NaN         NaN        NaN

**How many different year values are there?**

In [70]:
sal["Year"].value_counts()

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [71]:
sal["Year"].value_counts(dropna = True)

2014    38123
2013    37606
2012    36766
2011    36159
Name: Year, dtype: int64

In [72]:
sal.Year.unique()

array([2011, 2012, 2013, 2014], dtype=int64)

**Print out max and avg Totalpay**

In [73]:
#max
maxi = sal["TotalPay"]
maxi.max()


567595.43

In [74]:
#avg
maxi.mean()

74768.321971703

**How many records in the TotalPay column are there bigger than avg TotalPay**

In [75]:
sal[sal["TotalPay"] > sal["TotalPay"].mean()]

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
135701  135702    Christina S Jee   
135778  135779  Mary Ann T Abille   
135847  135848   Emilda E Reinosa   
135853  135854      David G Evans   
136063  136064         Nicole Joe   

                                              JobTitle    BasePay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  167411.18   
1                      CAPTAIN III (POLICE DEPARTMENT)  155966.02   
2                      CAPTAIN III (POLICE DEPARTMENT)  212739.13   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC   77916.00   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  134401.60   
...                                                ...        ...   
135701                              Nurse Practitioner   70635.61   
135778                                   Special Nurse   60889.34   
135847                                   Special Nurse   76305.74   
135853                                   Special Nurse   71178.15   
136063                                   Special Nurse   61276.59   

        OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  Year  \
0              0.00  400184.25       NaN  567595.43         567595.43  2011   
1         245131.88  137811.38       NaN  538909.28         538909.28  2011   
2         106088.18   16452.60       NaN  335279.91         335279.91  2011   
3          56120.71  198306.90       NaN  332343.61         332343.61  2011   
4           9737.00  182234.59       NaN  326373.19         326373.19  2011   
...             ...        ...       ...        ...               ...   ...   
135701         0.00    6550.41    771.88   77186.02          77957.90  2014   
135778      6815.67    9041.21    767.47   76746.22          77513.69  2014   
135847         0.00       0.00    763.08   76305.74          77068.82  2014   
135853      2748.15    2354.40    762.81   76280.70          77043.51  2014   
136063      8538.44    5078.67    748.95   74893.70          75642.65  2014   

        Notes         Agency  Status  
0         NaN  San Francisco     NaN  
1         NaN  San Francisco     NaN  
2         NaN  San Francisco     NaN  
3         NaN  San Francisco     NaN  
4         NaN  San Francisco     NaN  
...       ...            ...     ...  
135701    NaN  San Francisco     NaN  
135778    NaN  San Francisco     NaN  
135847    NaN  San Francisco     NaN  
135853    NaN  San Francisco     NaN  
136063    NaN  San Francisco     NaN  

[69489 rows x 13 columns]

In [76]:
len(sal[sal["TotalPay"] > sal["TotalPay"].mean()])

69489

**How much does ALBERT PARDINI make (including benefits)?**

In [62]:
sal[sal["EmployeeName"] == "ALBERT PARDINI"]["TotalPayBenefits"]

2    335279.91
Name: TotalPayBenefits, dtype: float64

**Who is the lowest paid person?**

In [67]:
sal[sal["TotalPayBenefits"] == sal["TotalPayBenefits"].min()]["EmployeeName"]

148653    Joe Lopez
Name: EmployeeName, dtype: object

**What are the unique Jobs in dataset?**

In [68]:
sal["JobTitle"].unique()

array(['GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY',
       'CAPTAIN III (POLICE DEPARTMENT)',
       'WIRE ROPE CABLE MAINTENANCE MECHANIC', ..., 'Conversion',
       'Cashier 3', 'Not provided'], dtype=object)

**List 3 the least common Jobs**

In [75]:

sal["JobTitle"].value_counts().tail(3)

COURT COMPUTER FACILITIES COORDINATOR             1
AUTOMOTIVE BODY AND FENDER WORKER SUPERVISOR I    1
VICTIM & WITNESS TECHNICIAN                       1
Name: JobTitle, dtype: int64

**How many people earned more than avg in 2012?**

In [82]:
len(sal[(sal["TotalPayBenefits"] >sal["TotalPayBenefits"].mean())& (sal["Year"] == 2012)])

20366

**How many people have a title of Manager in their jobs?**

In [88]:
#use apply function here
len(sal[sal.JobTitle.apply(lambda x: True if "manager"in x.lower() else False)])   

4110

**Take Id, EmployeeName, JobTitle, TotalPay and TotalPayBenefits columns with iloc and assign them as sal_new dataframe**

In [89]:
sal.head()

Id       EmployeeName                                        JobTitle  \
0   1     NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1   2       GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2   3     ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3   4  CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4   5    PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   

     BasePay  OvertimePay   OtherPay  Benefits   TotalPay  TotalPayBenefits  \
0  167411.18         0.00  400184.25       NaN  567595.43         567595.43   
1  155966.02    245131.88  137811.38       NaN  538909.28         538909.28   
2  212739.13    106088.18   16452.60       NaN  335279.91         335279.91   
3   77916.00     56120.71  198306.90       NaN  332343.61         332343.61   
4  134401.60      9737.00  182234.59       NaN  326373.19         326373.19   

   Year  Notes         Agency  Status  
0  2011    NaN  San Francisco     NaN  
1  2011    NaN  San Francisco     NaN  
2  2011    NaN  San Francisco     NaN  
3  2011    NaN  San Francisco     NaN  
4  2011    NaN  San Francisco     NaN

In [93]:
sal_new= sal.iloc[:,[0,1,2,7,8]]
sal_new

Id       EmployeeName  \
0            1     NATHANIEL FORD   
1            2       GARY JIMENEZ   
2            3     ALBERT PARDINI   
3            4  CHRISTOPHER CHONG   
4            5    PATRICK GARDNER   
...        ...                ...   
148649  148650      Roy I Tillery   
148650  148651       Not provided   
148651  148652       Not provided   
148652  148653       Not provided   
148653  148654          Joe Lopez   

                                              JobTitle   TotalPay  \
0       GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY  567595.43   
1                      CAPTAIN III (POLICE DEPARTMENT)  538909.28   
2                      CAPTAIN III (POLICE DEPARTMENT)  335279.91   
3                 WIRE ROPE CABLE MAINTENANCE MECHANIC  332343.61   
4         DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)  326373.19   
...                                                ...        ...   
148649                                       Custodian       0.00   
148650                                    Not provided       0.00   
148651                                    Not provided       0.00   
148652                                    Not provided       0.00   
148653                      Counselor, Log Cabin Ranch    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 5 columns]

**Take the columns betweeen EmployeeName and TotalPayBenefits with loc and assign them as sal_new df** 

In [99]:
sal_new= sal.loc[:,"EmployeeName":"TotalPayBenefits"]
sal_new

EmployeeName                                        JobTitle  \
0          NATHANIEL FORD  GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY   
1            GARY JIMENEZ                 CAPTAIN III (POLICE DEPARTMENT)   
2          ALBERT PARDINI                 CAPTAIN III (POLICE DEPARTMENT)   
3       CHRISTOPHER CHONG            WIRE ROPE CABLE MAINTENANCE MECHANIC   
4         PATRICK GARDNER    DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)   
...                   ...                                             ...   
148649      Roy I Tillery                                       Custodian   
148650       Not provided                                    Not provided   
148651       Not provided                                    Not provided   
148652       Not provided                                    Not provided   
148653          Joe Lopez                      Counselor, Log Cabin Ranch   

          BasePay  OvertimePay   OtherPay  Benefits   TotalPay  \
0       167411.18         0.00  400184.25       NaN  567595.43   
1       155966.02    245131.88  137811.38       NaN  538909.28   
2       212739.13    106088.18   16452.60       NaN  335279.91   
3        77916.00     56120.71  198306.90       NaN  332343.61   
4       134401.60      9737.00  182234.59       NaN  326373.19   
...           ...          ...        ...       ...        ...   
148649       0.00         0.00       0.00       0.0       0.00   
148650        NaN          NaN        NaN       NaN       0.00   
148651        NaN          NaN        NaN       NaN       0.00   
148652        NaN          NaN        NaN       NaN       0.00   
148653       0.00         0.00    -618.13       0.0    -618.13   

        TotalPayBenefits  
0              567595.43  
1              538909.28  
2              335279.91  
3              332343.61  
4              326373.19  
...                  ...  
148649              0.00  
148650              0.00  
148651              0.00  
148652              0.00  
148653           -618.13  

[148654 rows x 8 columns]

**Print out the names of the employees who earn more than min, but less than avg**

In [104]:
sal[(sal["TotalPayBenefits"] > sal["TotalPayBenefits"].min())& (sal["TotalPayBenefits"]<sal["TotalPayBenefits"].mean())]\
[["EmployeeName","TotalPayBenefits"]]


EmployeeName  TotalPayBenefits
10806          KWE LEE          93691.15
10807   MIGUEL CARO JR          93682.74
10808    JOANNE MORRIS          93680.53
10809    LAYLA WELBORN          93676.88
10810          LE BANH          93675.39
...                ...               ...
148648     Leon Walker              0.00
148649   Roy I Tillery              0.00
148650    Not provided              0.00
148651    Not provided              0.00
148652    Not provided              0.00

[75649 rows x 2 columns]

___

<p style="text-align: center;"><img src="https://docs.google.com/uc?id=1lY0Uj5R04yMY3-ZppPWxqCr5pvBLYPnV" class="img-fluid" 
alt="CLRSWY"></p>

## <p style="background-color:#FDFEFE; font-family:newtimeroman; color:#9d4f8c; font-size:100%; text-align:center; border-radius:10px 10px;">WAY TO REINVENT YOURSELF</p>

___